Support mounting of external secrets
bakdata/common-kafka-streams pull request #225
Opened 2024-05-16 07:32 UTC by torbsto

2024-05-16 07:41 UTC, philipp94831 reviewed
Did you test it?

2024-06-10 05:22 UTC, torbsto commented
> Did you test it?

Tested :+1:

2024-06-10 06:21 UTC, philipp94831 requested changes

2024-06-10 06:21 UTC, philipp94831 commented on charts/producer-app/templates/pod.yaml
> +          {{- end }}
```suggestion
      {{- end }}
```

2024-06-10 06:21 UTC, philipp94831 commented on charts/producer-app-cleanup-job/templates/job.yaml
> +          {{- if or (.Values.files) (.Values.secretFilesRefs)}}
```suggestion
          {{- if or (.Values.files) (.Values.secretFilesRefs) }}
```

2024-06-10 06:21 UTC, philipp94831 commented on charts/producer-app/templates/pod.yaml
> +    {{- if or (.Values.files) (.Values.secretFilesRefs)}}
```suggestion
    {{- if or (.Values.files) (.Values.secretFilesRefs) }}
```

2024-06-10 06:21 UTC, philipp94831 commented on charts/streams-app-cleanup-job/templates/job.yaml
> +         {{- if or (.Values.files) (.Values.secretFilesRefs)}}
```suggestion
          {{- if or (.Values.files) (.Values.secretFilesRefs) }}
```

2024-06-10 06:21 UTC, philipp94831 commented on charts/streams-app-cleanup-job/templates/job.yaml
> +      {{- if .Values.files }}
```suggestion
        {{- if .Values.files }}
```

2024-06-10 06:21 UTC, philipp94831 commented on charts/streams-app-cleanup-job/templates/job.yaml
>        {{- end }}
```suggestion
        {{- end }}
```

2024-06-10 06:21 UTC, philipp94831 commented on charts/producer-app/templates/pod.yaml
> +    {{- end}}
```suggestion
    {{- end }}
```

2024-06-10 06:21 UTC, philipp94831 commented on charts/producer-app-cleanup-job/templates/job.yaml
> +            {{- end}}
```suggestion
            {{- end }}
```

2024-06-10 06:21 UTC, philipp94831 commented on charts/producer-app-cleanup-job/templates/job.yaml
> +        {{- end}}
```suggestion
        {{- end }}
```

2024-06-10 06:21 UTC, philipp94831 commented on charts/producer-app/templates/pod.yaml
> +      {{- end}}
```suggestion
      {{- end }}
```

2024-06-10 06:21 UTC, philipp94831 commented on charts/streams-app-cleanup-job/templates/job.yaml
> +            {{- end}}
```suggestion
            {{- end }}
```

2024-06-10 06:21 UTC, philipp94831 commented on charts/streams-app-cleanup-job/templates/job.yaml
> +        {{- end}}
```suggestion
        {{- end }}
```

2024-06-10 06:21 UTC, philipp94831 commented on charts/streams-app/templates/deployment.yaml
> +            {{- end}}
```suggestion
            {{- end }}
```

2024-06-10 06:21 UTC, philipp94831 commented on charts/streams-app/templates/deployment.yaml
> +        {{- end}}
```suggestion
        {{- end }}
```

2024-06-10 06:46 UTC, philipp94831 requested changes
Please add documentation to READMEs

2024-06-10 06:56 UTC, philipp94831 approved these changes

2024-06-10 07:27 UTC, merged